-- Database Selection / Creation
CREATE DATABASE IF NOT EXISTS disaster_aqi_system;
USE disaster_aqi_system;

-- ==========================================
-- 1. Real API Environmental Data Table
-- Purpose: Store past & real-time environmental data fetched from APIs (WAQI, Open-Meteo, etc.)
-- ==========================================
CREATE TABLE IF NOT EXISTS api_environmental_data (
    id INT AUTO_INCREMENT PRIMARY KEY,          -- Unique ID for each record
    timestamp DATETIME NOT NULL,                -- Time when data was recorded
    latitude DECIMAL(10, 8),                    -- GPS Latitude
    longitude DECIMAL(11, 8),                   -- GPS Longitude
    aqi INT,                                    -- API reported AQI
    pm25 FLOAT,                                 -- PM 2.5 concentration
    pm10 FLOAT,                                 -- PM 10 concentration
    temperature FLOAT,                          -- Temperature in Celsius
    humidity FLOAT,                             -- Humidity percentage
    pressure FLOAT,                             -- Atmospheric pressure (hPa)
    wind_speed FLOAT,                           -- Wind speed (m/s)
    rainfall FLOAT,                             -- Rainfall (mm)
    data_source VARCHAR(255),                   -- Source of data (e.g., 'WAQI', 'Open-Meteo')
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Record creation timestamp
    
    -- Indexes for faster querying
    INDEX idx_timestamp (timestamp),
    INDEX idx_lat_lon (latitude, longitude)
);

-- Note: For PostgreSQL compatibility:
-- Replace 'INT AUTO_INCREMENT PRIMARY KEY' with 'SERIAL PRIMARY KEY'
-- 'DATETIME' can be 'TIMESTAMP'

-- ==========================================
-- 2. AQI ML Predictions Table
-- Purpose: Store AQI predictions generated by the ML models for the future (next 24h, next 7 days)
-- ==========================================
CREATE TABLE IF NOT EXISTS aqi_predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,          -- Unique Prediction ID
    prediction_date DATETIME NOT NULL,          -- The future date/time being predicted
    predicted_aqi FLOAT,                        -- Predicted AQI value
    predicted_pm25 FLOAT,                       -- Predicted PM 2.5
    predicted_pm10 FLOAT,                       -- Predicted PM 10
    model_name VARCHAR(100),                    -- Name of the model used (e.g., 'RandomForest', 'LSTM')
    model_accuracy FLOAT,                       -- Accuracy score of the model at time of prediction (MAE/R2)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- When this prediction was made
    
    -- Indexes
    INDEX idx_pred_date (prediction_date),
    INDEX idx_model (model_name)
);

-- ==========================================
-- 3. Disaster Prediction Results Table
-- Purpose: Store binary/probabilistic disaster predictions (Flood, Heatwave, Pollution)
-- ==========================================
CREATE TABLE IF NOT EXISTS disaster_predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,          -- Unique Prediction ID
    prediction_date DATETIME NOT NULL,          -- Target date for prediction
    disaster_occurred BOOLEAN,                  -- Predicted Yes (1) / No (0)
    disaster_probability FLOAT,                 -- Probability percentage (0-100)
    disaster_type VARCHAR(100),                 -- Type: 'Heatwave', 'Flood', 'Pollution', 'None'
    model_name VARCHAR(100),                    -- Model used (e.g., 'RandomForestClassifier')
    model_accuracy FLOAT,                       -- Model accuracy metric
    risk_level VARCHAR(50),                     -- 'Low', 'Medium', 'High', 'Critical'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- When the prediction was run
    
    -- Indexes
    INDEX idx_disaster_date (prediction_date),
    INDEX idx_risk_level (risk_level)
);

-- ==========================================
-- view_latest_predictions
-- Example Query: Fetch latest AQI prediction
-- ==========================================
-- SELECT * FROM aqi_predictions ORDER BY created_at DESC LIMIT 1;

-- ==========================================
-- view_past_data
-- Example Query: Fetch past environmental data for a specific date
-- ==========================================
-- SELECT * FROM api_environmental_data WHERE DATE(timestamp) = '2023-10-27';
